base_url = "https://atinba.github.io"
compile_sass = true
build_search_index = true
generate_feeds = false

taxonomies = [
    { name = "tags" },
    { name = "categories" },
    { name = "contexts" },
]


[markdown]
highlight_code = true


[extra]
header_nav = [
    { name = "~home", url = "/" },
    { name = "books", url = "/books" },
    { name = "music", url = "/music" },
    { name = "math+phy", url = "/math-and-physics" },
]
