base_url = "https://atinba.github.io"
compile_sass = true
build_search_index = true

generate_feeds = true

taxonomies = [
    { name = "tags" },
    { name = "categories" },
    { name = "contexts" },
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true


[extra]
header_nav = [
    { name = "~", url = "/" },
    #{ name = "#tags", url = "/no-style-please/tags" },
    #{ name = "+categories", url = "/no-style-please/categories" },
    #{ name = "@contexts", url = "/no-style-please/contexts" },
]
